name: fullbooker
description: "Your favorite events await!"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.27.4"

dependencies:
  async_redux: ^24.0.7
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dropdown_button2: ^2.3.9
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.1
  google_sign_in: ^6.3.0
  heroicons: ^0.11.0
  http: ^1.3.0
  http_parser: ^4.1.2
  intl: ^0.19.0
  json: ^0.20.4
  map_location_picker: ^1.3.3
  otp_pin_field: ^1.3.2
  path: ^1.9.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  sembast: ^3.8.3
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  uuid: ^4.5.1
  video_player: ^2.9.3
dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo_splash.png
    - assets/images/overview1/
    - assets/images/overview2/
    - assets/images/overview3/
    - assets/icons/
    - assets/defaultImg.png
    - assets/animations/pin.json
