name: fullbooker
description: "Your favourite events await!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json: ^0.20.2
  http: ^1.2.2
  sembast: ^3.8.1+1
  flutter_staggered_grid_view: ^0.7.0
  path: 
  path_provider: ^2.1.5
  otp_pin_field: ^1.3.2
  file_picker: ^8.3.1
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  lottie: ^1.4.2
  shimmer: ^2.0.0
  map_location_picker: ^1.3.3
  http_parser: ^4.0.2
  video_player: ^2.9.2
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3
  qr_flutter: ^4.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/logo_splash.png
    - assets/images/overview1/
    - assets/images/overview2/
    - assets/images/overview3/
    - assets/icons/
    - assets/defaultImg.png
    - assets/annimations/pin.json
