// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNfKDNyfDuk9U8Y7lb9x8H3BY-r7NhPg',
    appId: '1:273711950325:android:52a1e99dd3c2e77166d8bc',
    messagingSenderId: '273711950325',
    projectId: 'fullbooker-ddf43',
    storageBucket: 'fullbooker-ddf43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0AHTbb4s2HkVj-MPeQWsJx6AkFDAZ-WU',
    appId: '1:273711950325:ios:b157d8ef0daaa3dc66d8bc',
    messagingSenderId: '273711950325',
    projectId: 'fullbooker-ddf43',
    storageBucket: 'fullbooker-ddf43.firebasestorage.app',
    androidClientId: '273711950325-679v9ejl8g260oigrl5nuf4oshnspgt5.apps.googleusercontent.com',
    iosClientId: '273711950325-06nu3ncq2pvrma95odiltrpjn5l2t79a.apps.googleusercontent.com',
    iosBundleId: 'com.fullbooker.fullbooker',
  );
}
