name: Fullbooker CI/CD Workflow

on: [push]

jobs:
  ci-checks:
    name: fullbooker CI checks
    timeout-minutes: 15
    runs-on: macos-13
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "3.27.4"

      - name: Install flutter dependencies
        run: flutter pub get
